### ISSUE TITLE
Randlib depends on atmel-rf-driver

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbed-client-randlib#5]
Randlib has a hard dependency on atmel-rf-driver, something that needs to be fixed if you ever want to support other PHYs.

**Comment by kjbracey-arm** [comment]
It has a dependency on someone in the system providing the arm_hal_random.h APIs. There's no direct dependency on any radio driver.

This module has no stated dependencies, and just hopes that someone is already providing the necessary HAL layer.

Typically whoever implements arm_random_seed_get() uses rf_read_random(), but the intent is that any radio PHY should provide that call, so it's not supposed to be atmel-rf-driver specific.

Maybe there is a stated atmel-rf-driver dependency somewhere, but it's not here.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2706

**Comment by stevew817** [comment]
Sorry, my mistake. It's not in randlib, but rather in the nanostack HAL. I'll log the issue there.
